name: Benchmark runner

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COREPACK_ENABLE_AUTO_PIN: 0
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          corepack prepare yarn@stable --activate
      - run: pnpm --dir=benchmarks install
      - run: pnpm --dir=benchmarks run benchmark
      - run: pnpm --dir=benchmarks run benchmark
      - run: pnpm --dir=benchmarks run benchmark
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "chore: update benchmarks"
          branch: main
